export const LOCAL_BASE_URL = "http://127.0.0.1:5001/deadlibrary-53c38/us-central1/"

export const ENDPOINTS = {
    button: `${LOCAL_BASE_URL}generateButton`,
    card: `${LOCAL_BASE_URL}generateCard`,
    componentList: `${LOCAL_BASE_URL}generateComponentList`,
    formField: `${LOCAL_BASE_URL}generateFormField`,
    formGroup: `${LOCAL_BASE_URL}generateFormGroup`,
    gridList: `${LOCAL_BASE_URL}generateGridList`,
    icon: `${LOCAL_BASE_URL}generateIcon`,
    iconParagraph: `${LOCAL_BASE_URL}generateIconParagraph`,
    imageCarousel: `${LOCAL_BASE_URL}generateImageCarousel`,
    imageDiv: `${LOCAL_BASE_URL}generateImageDiv`,
    lazyPage: `${LOCAL_BASE_URL}generateLazyPage`,
    listButton: `${LOCAL_BASE_URL}generateListButton`,
    loadingBar: `${LOCAL_BASE_URL}generateLoadingBar`,
    loadingSpinner: `${LOCAL_BASE_URL}generateLoadingSpinner`,
    menu: `${LOCAL_BASE_URL}generateMenu`,
    mobileToolbar: `${LOCAL_BASE_URL}generateMobileToolbar`,
    modal: `${LOCAL_BASE_URL}generateModal`,
    radioButton: `${LOCAL_BASE_URL}generateRadioButton`,
    select: `${LOCAL_BASE_URL}generateSelect`,
    slideToggle: `${LOCAL_BASE_URL}generateSlideToggle`,
    tabs: `${LOCAL_BASE_URL}generateTabs`,
    theme: `${LOCAL_BASE_URL}generateTheme`,
    titleButton: `${LOCAL_BASE_URL}generateTitleButton`,
    titleList: `${LOCAL_BASE_URL}generateTitleList`,
    titleParagraph: `${LOCAL_BASE_URL}generateTitleParagraph`,
    titleParagraphButton: `${LOCAL_BASE_URL}generateTitleParagraphButton`,
    titleSubList: `${LOCAL_BASE_URL}generateTitleSubList`,
    titleSubListButton: `${LOCAL_BASE_URL}generateTitleSubListButton`,
    titleSubParagraph: `${LOCAL_BASE_URL}generateTitleSubParagraph`,
    titleSubParagraphButton: `${LOCAL_BASE_URL}generateTitleSubParagraphButton`,
    toolbar: `${LOCAL_BASE_URL}generateToolbar`,
}
