#!/usr/bin/env node
import { Command } from "commander";
import { generateGridList } from './commands/generateGridList';
import { generateCard } from './commands/generateCard';
import { generateLoadingSpinner } from "./commands/generateLoadingSpinner";
import { generateToolbar } from "./commands/generateToolbar";
import { generateTitleParagraph } from "./commands/generateTitleParagraph";
import { generateComponentList } from "./commands/generateComponentList";
import { generateImageDiv } from './commands/generateImageDiv';
import { generateTitleButton } from "./commands/generateTitleButton";
import { generateTitleList } from "./commands/generateTitleList";
import { generateTitleSubList } from "./commands/generateTitleSubList";
import { generateTitleSubListButton } from "./commands/generateTitleSubListButton";
import { generateTitleSubParagraph } from "./commands/generateTitleSubParagraph";
import { generateTitleSubParagraphButton } from "./commands/generateTitleSubParagraphButton";
import { generateTitleParagraphButton } from "./commands/generateTitleParagraphButton";
import { generateTheme } from "./commands/generateTheme";
import { generateButton } from "./commands/generateButton";
import { generateFormField } from "./commands/generateFormField";
import { generateMobileToolbar } from "./commands/generateMobileToolbar";
import { generateMenu } from "./commands/generateMenu";
import { generateFormGroup } from "./commands/generateFormGroup";
import { generateTabs } from "./commands/generateTabs";
import { generateIcon } from "./commands/generateIcon";
import { generateIconParagraph } from "./commands/generateIconParagraph";
import { generateImageCarousel } from "./commands/generateImageCarousel";
import { generateLazyPage } from "./commands/generateLazyPage";
import { generateLoadingBar } from "./commands/generateLoadingBar";
import { generateSelect } from "./commands/generateSelect";
import { generateRadioButton } from "./commands/generateRadioButton";
import { generateModal } from "./commands/generateModal";
import { generateSlideToggle } from "./commands/generateSlideToggle";
import { generateDatePicker } from "./commands/generateDatePicker";
import { generateDivider } from "./commands/generateDivider";
import { generateSlider } from "./commands/generateSlider";
import { generateListButton } from "./commands/generateListButton";
import { generateAutocomplete } from "./commands/generateAutocomplete";
import { generateButtonBadge } from "./commands/generateButtonBadge";
import { generateBottomModal } from "./commands/generateBottomModal";
import { generateChipList } from "./commands/generateChipList";
import { generateComponentCarousel } from "./commands/generateComponentCarousel";
import { generateSideNav } from "./commands/generateSideNav";
import { generateTimePicker } from "./commands/generateTimePicker";
import { generateTooltip } from "./commands/generateTooltip";
import { generateButtonToggle } from "./commands/generateButtonToggle";
import { generateExpansionPanel } from "./commands/generateExpansionPanel";
import { generateCheckboxList } from "./commands/generateCheckboxList";
import { generateBreakpointService } from "./commands/generateBreakpointService";
import { generateThemeChangerMenu } from "./commands/generateThemeChangerMenu";
import { generateThemeChangerService } from "./commands/generateThemeChangerService";
import { generatePhoneDirective } from "./commands/generatePhoneDirective";
import { generateAppConfig } from "./commands/generateAppConfig";
import { generateIndexConfig } from "./commands/generateIndexConfig";
import { generateScrollService } from "./commands/generateScrollService";
import { generateLoadingService } from "./commands/generateLoadingService";
import { g } from "./commands/g";

const program = new Command();

program
    .name('dead')
    .description('Command line interface for DeadLibrary.')
    .version('1.54.0')

g(program);

generateAppConfig(program);
generateAutocomplete(program);
generateBottomModal(program);
generateBreakpointService(program);
generateButton(program);
generateButtonBadge(program);
generateButtonToggle(program);
generateCard(program);
generateCheckboxList(program);
generateChipList(program);
generateComponentCarousel(program);
generateComponentList(program);
generateDatePicker(program);
generateDivider(program);
generateExpansionPanel(program);
generateFormField(program);
generateFormGroup(program);
generateGridList(program);
generateIcon(program);
generateIconParagraph(program);
generateImageCarousel(program);
generateImageDiv(program);
generateIndexConfig(program);
generateLazyPage(program);
generateListButton(program);
generateLoadingBar(program);
generateLoadingService(program);
generateLoadingSpinner(program);
generateMobileToolbar(program);
generateModal(program);
generateMenu(program);
generatePhoneDirective(program);
generateRadioButton(program);
generateScrollService(program);
generateSelect(program);
generateSideNav(program);
generateSlider(program);
generateSlideToggle(program);
generateTabs(program);
generateToolbar(program);
generateTooltip(program);
generateTimePicker(program);
generateTitleParagraph(program);
generateTitleSubParagraphButton(program);
generateTitleButton(program);
generateTitleList(program);
generateTitleSubList(program);
generateTitleSubListButton(program);
generateTitleSubParagraph(program);
generateTitleParagraphButton(program);
generateTheme(program);
generateThemeChangerMenu(program);
generateThemeChangerService(program);

program.parse(process.argv);
